Add SimTLMem
ucb-bar/testchipip pull request #161
Opened 2023-03-18 07:45 UTC by joey0320

Add a SimTLMem which can be used in the simulation TestHarness when using a TL punch through

2023-04-09 08:59 UTC, jerryz123 requested changes
Can you rebase this against master chipyard and testchipip to capture the chisel3.5.6 bump?

2023-04-09 08:59 UTC, jerryz123 commented on src/main/scala/SimTLMem.scala
> +// srams.foreach{ s => s.node := TLBuffer() := TLFragmenter() := xbar }
Remove the commented line

2023-04-10 02:38 UTC, joey0320 commented on src/main/scala/SimTLMem.scala
> +// srams.foreach{ s => s.node := TLBuffer() := TLFragmenter() := xbar }
Yes sir

2023-04-10 02:43 UTC, jerryz123 requested changes

2023-04-10 02:43 UTC, jerryz123 commented on src/main/scala/SimTLMem.scala
> +import freechips.rocketchip.config.Parameters
This needs to be org.chipsalliance.cde.config.Parameters

2023-04-10 06:34 UTC, jerryz123 approved these changes
Can you rebase this against master chipyard and testchipip to capture the chisel3.5.6 bump?

2023-04-10 06:34 UTC, merged