Organize TestChipIP into sub-packages
ucb-bar/testchipip pull request #210
Opened 2023-12-19 19:28 UTC by jerryz123

This makes it a bit easier to discover parts of testchipip.

The README is also updated.

2023-12-19 22:38 UTC, abejgonzalez requested changes

2023-12-19 22:38 UTC, abejgonzalez commented on src/main/scala/serdes/.#Adapter.scala
Extra file.

2023-12-19 22:38 UTC, abejgonzalez commented on src/main/scala/serdes/Adapter.scala
> +class UARTToSerial(freqHz: BigInt, uartParams: UARTParams) extends Module {
Duplicate? There is an `UARTToSerial` file anyways.

2023-12-20 20:40 UTC, jerryz123 commented
@kenhoberkeley @T-K-233 any thoughts? Else I will merge

2023-12-20 21:46 UTC, T-K-233 approved these changes

2023-12-21 17:53 UTC, merged